name: Daddy's Deals
version: 1.0.0
slug: daddys_deals
description: >
  A parental control system to manage chores and rewards with Daddy Dollars.
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386
startup: application
boot: auto
ports:
  8080/tcp: 8080
host_network: true
options: {}
schema: {}
